logs

diff --git a/.github/workflows/ecr.yml b/.github/workflows/ecr.yml
--- a/.github/workflows/ecr.yml
+++ b/.github/workflows/ecr.yml
@@ -35,6 +35,7 @@ env:
   IMAGE_TAG: ${{ github.sha }}
   ORG: ${{ github.repository_owner }}
   BRANCH: ${{ github.event_name == 'delete' && github.event.ref || (github.head_ref || github.ref_name) }}
+  LOG_file: log.out
 
 jobs:
   ecr-publish:
@@ -150,6 +151,11 @@ jobs:
             aws $AWS_CLI_SERVICE describe-images --repository-name $ECR_REPOSITORY_NAME --image-ids imageTag=latest --output json
           }
           func_ecr () {
+            # log save
+            exec 3>&1 4>&2
+            trap 'exec 2>&4 1>&3' 0 1 2 3
+            exec 1>$LOG_FILE 2>&1
+
             # create/push/delete
             if [[ "${{ github.event_name }}" == "create" || ("${{ github.event_name }}" == "workflow_dispatch" && "${{ inputs.event }}" == "create") ]]; then
               func_ecr_create
@@ -194,5 +200,11 @@ jobs:
             echo DOCKERFILE_ARGS:: $DOCKERFILE_ARGS
 
             # run function
-            func_ecr
+            $(func_ecr)
+
+            # log print
+            echo -e '\033[46mLOGS\033[0m'; cat $LOG_FILE
+            if [ -n "$(grep -i error $LOG_FILE)" ]; then
+              echo -e '\033[41mERRORS\033[0m'; grep -ni error $LOG_FILE | sed 's/$/\n/'; exit 10
+            fi
           done
